### ISSUE TITLE
Broken notes after error (when using S3 with server-side encryption)

### ISSUE THREAD

**Issue by orcu** [nextcloud/notes#650]
Hello,
After fresh install of the app, I received the following error when trying to create a new note from the app page on the browser:
`Error: (New note.txt) Legacy cipher is no longer supported!`

I am not able to solve this problem and from what I understand it may be caused by something other then the notes app; however, these new notes are hung in the notes app. They are seemingly created on the browser (as seen in the note list on the left side of the browser) however they do not sync, they cannot be retrieved or edited (Error: (New note.txt) Legacy cipher is no longer supported!). They cannot be deleted (Error during preparing note for deletion.). On the other hand, they can be renamed. Locally created files sync well an can be edited on the browser. Removing and reinstalling the notes app does not seem to have any effect, the broken notes appear right after reinstall of the app.

**Comment by korelstar** [comment]
Please provide details about your setup. For this purpose, the issue template points to many relevant aspects. Use it!

In this case, please also provide detailed information about the usage of server-side encryption or something similar.

**Comment by pranavb25** [comment]
Facing the exact same issue.

Running the latest stable version of NC on Ubuntu. 

Notes Version - 4.0.2
Server - Nginx
Encryption - Server side encryption with default encryption module enabled.
Primary Storage - AWS S3

Based on the logs, I am receiving the following errors:

**PHP Error:**

Error: stream_wrapper_register():  Protocol ocencryption:// is already defined. at  /var/www/nextcloud/lib/private/Files/Stream/Encryption.php#203

**Notes Error:**

OC\ServerNotAvailableException: Legacy cipher is no longer supported!

**Comment by orcu** [comment]
yes, s3 & server side encryption

**Comment by korelstar** [comment]
I was able to reproduce the issue. :tada: 

It looks like an old workaround for fixing problems with server-side encryption, now causes this issue. After removing the respecting code, everything works fine! Would you mind to review my PR #690 @orcu @pranavb25 ? The changes are rather simple, you could try to change them manually in your installation.

-----

Just for the protocol: I used the following `docker-compose.yml` file for reproducing the issue:

```
version: '2'

services:
        app:
                image: nextcloud:20
                depends_on:
                        - minio
                ports:
                        - 8080:80
                volumes:
                        - ./nextcloud:/var/www/html
                environment:
                        - SQLITE_DATABASE=nextcloud
                        - NEXTCLOUD_ADMIN_USER=admin
                        - NEXTCLOUD_ADMIN_PASSWORD=admin
                        - OBJECTSTORE_S3_HOST=minio
                        - OBJECTSTORE_S3_PORT=9000
                        - OBJECTSTORE_S3_SSL=false
                        - OBJECTSTORE_S3_BUCKET=nextcloud
                        - OBJECTSTORE_S3_KEY=s3key
                        - OBJECTSTORE_S3_SECRET=s3secret
                        - OBJECTSTORE_S3_USEPATH_STYLE=true

        minio:
                networks:
                        default:
                                aliases:
                                        - nextcloud.minio
                image: minio/minio
                ports:
                        - 9000:9000
                volumes:
                        - ./data:/data
                environment:
                        - MINIO_ACCESS_KEY=s3key
                        - MINIO_SECRET_KEY=s3secret
                command:
                        server /data
```
