### ISSUE TITLE
(Doctrine\DBAL\Exception\InvalidFieldNameException)

### ISSUE THREAD

**Issue by PipeItToDevNull** [nextcloud/notes#661]
When opening existing notes the above error occurs. Removing Notes from the root of a user results in the same error when adding your first new note.

## Steps to reproduce
1. Open or create a note

### Expected behaviour
Notes are opened, or a new one is made

### Actual behaviour
In the browser console, when making your first note
`Error: Request failed with status code 500`
`Server error while updating list of notes: Reading notes from filesystem has failed. (Doctrine\DBAL\Exception\InvalidFieldNameException)`

When just opening existing notes, error in the browser console and the Notes application window
`Reading notes from filesystem has failed. (Doctrine\DBAL\Exception\InvalidFieldNameException)`

## Server
Please complete the following information.

- Notes app version: 4.0.2
- Nextcloud version: 20.0.0 and 20.0.4
- OS: Docker on Linux
- Web server: Apache
- PHP version: 
- Database: Maria

**Nextcloud configuration:**

<details>
```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.dev0.sh"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "overwrite.cli.url": "https:\/\/cloud.dev0.sh",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "theme": "",
        "loglevel": "0",
        "app_install_overwrite": [
            "calendar",
            "twofactor_yubikey",
            "spreed",
            "breezedark"
        ],
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

## Client
Please complete the following information.

- Browser (incl. version): Firefox 84.0.1 and Chrome 87.0.4280.88
 - OS: Windows 10

**Comment by korelstar** [comment]
Please have a look at your Nextcloud server log (`nextcloud.log`) and search for a stack trace for that exception. This would be very helpful.

Which docker tag do you use? Does this happen out of the box after installing a clean docker image or did you have done an update of the notes app from an older version?

Please check also Nextcloud's [Warnings on admin page](https://docs.nextcloud.com/server/20/admin_manual/configuration_server/security_setup_warnings.html) under https://yourserver/index.php/settings/admin/overview .

**Comment by Lavikjo** [comment]
Hey, I have a similar issue and investigated the situation further.

Here is the output from occ log:watch when trying to access Nextcloud Notes app: [gist](https://gist.github.com/Lavikjo/bd9aa3b9c8ea0433301a0f407901fa58)

This bug occurred after updating the Nextcloud main version.

By checking the columns in table oc_notes_meta it seems to indeed be missing column named 'id': [gist](https://gist.github.com/Lavikjo/34c3a51d3dba7f3da6c8e83fb47596eb )

Has the file_id column been renamed to id at some point leading to this issue?

**Comment by Lavikjo** [comment]
Fixed my issue by manually adding column 'id' and setting it as auto incrementing primary key.

**Comment by korelstar** [comment]
@Lavikjo Thanks for the detailed log! The column `id` always existed and it is correctly defines in the database script: https://github.com/nextcloud/notes/blob/master/lib/Migration/Version3005Date20200528204431.php - so I have no idea, why the column got lost. :-(

> This bug occurred after updating the Nextcloud main version.

From which version to which version did you updated? Is it correct that it worked before?

**Comment by Lavikjo** [comment]
Yeah, I also wondered what happened with the column as I used the migration file as a reference on how the table should look like.

I updated from Nextcloud 19 to 20 version. It was working before that. I'm running NC in docker-container if that makes any difference.

**Comment by PipeItToDevNull** [comment]
I too run this in docker, and likely hit the issue moving from 19 to 20

**Comment by korelstar** [comment]
I tried to reproduce this issue, but I wasnt' able to do so. I used the following `docker-composer.yml`:

```
version: '2'

services:
        app:
                image: nextcloud:19
                ports:
                        - 8080:80
                volumes:
                        - ./nextcloud:/var/www/html
                environment:
                        - SQLITE_DATABASE=nextcloud
                        - NEXTCLOUD_ADMIN_USER=admin
                        - NEXTCLOUD_ADMIN_PASSWORD=admin
```

Then I proceeded with the following steps:

- start the container (`docker-compose up -d`)
- open http://localhost:8080/
- install Notes app
- open Notes app
- create some notes
- shut down the container (`docker-compose down`)
- change image in `docker-composer.yml` to `nextcloud:20`
- start the container (`docker-compose up -d`)
- open http://localhost:8080/apps/notes/
- open existing notes
- change existing notes
- create new notes

The error did not happen to me. What's the difference? Could you please provide detailed steps in order to reproduce the error?

**Comment by PipeItToDevNull** [comment]
I have been running this for years, I doubt I would be able to reproduce this on command. The solution seems to be adding in a database table, but I am in no way familiar enough with SQL to make up such commands on the fly.

**Comment by Lavikjo** [comment]
@korelstar One difference I can spot between your example is the usage of sqlite instead of mariadb. Not sure if this is the culprit, though.

@PipeItToDevNull for massaging your notes database table back in to order I used the following commands: [gist](https://gist.github.com/Lavikjo/b4288706f86d3fc474bc659e2dab1c7a) Hope this works for you aswell!

**Comment by korelstar** [comment]
@Lavikjo I've tried it with mariadb, too - but I still can't reproduce the issue: :disappointed: 

```
version: '2'

services:
        app:
                image: nextcloud:19
                depends_on:
                        - db
                ports:
                        - 8080:80
                volumes:
                        - ./nextcloud:/var/www/html
                environment:
                        - NEXTCLOUD_ADMIN_USER=admin
                        - NEXTCLOUD_ADMIN_PASSWORD=admin
                        - MYSQL_HOST=db
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
                        - MYSQL_PASSWORD=nextcloud

        db:
                image: mariadb
                command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
                volumes:
                        - ./db:/var/lib/mysql
                environment:
                        - MYSQL_ROOT_PASSWORD=mysql
                        - MYSQL_DATABASE=nextcloud
                        - MYSQL_USER=nextcloud
                        - MYSQL_PASSWORD=nextcloud
```
